sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t Vivek-0206/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Vivek-0206/docker-react npm test